### ISSUE TITLE
字体路径问题

### ISSUE THREAD

**Issue by shmilyfuu** [mingsky-ai/ComfyUI-MingNodes#7]
当我使用--output-directory参数启动comfyui时，节点报错

`[ERROR] An error occurred while retrieving information for the 'AddWaterMarkNode' node.
Traceback (most recent call last):
  File "N:\CondaComfyUI\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "N:\CondaComfyUI\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "N:\CondaComfyUI\ComfyUI\custom_nodes\ComfyUI-MingNodes\nodes\add_watermark.py", line 54, in INPUT_TYPES
    files = [f for f in os.listdir(font_path) if os.path.isfile(os.path.join(font_path, f))]
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'N:\\CondaComfyUI\\Output_Works\\ComfyUI-MingNodes\\fonts'`

Output_Works是我使用--output-directory定义的输出目录。似乎节点判断字体的路径有些问题，希望能得到修复

**Comment by mingsky-ai** [comment]
自定义目录有点问题，因为我代码里面是写了一个获取output路径然后转到插件路径下，你改可能会有问题

**Comment by shmilyfuu** [comment]
请问目前有修复计划吗？

**Comment by ZXCMiller** [comment]
> 自定义目录有点问题，因为我代码里面是写了一个获取output路径然后转到插件路径下，你改可能会有问题

我也遇到这个报错 很头疼 什么时候能修复呢？

**Comment by LilenXu** [comment]
好像是文件名不一样，在add_watermark.py代码里53行把ComfyUI-MingNodes改为ComfyUI-MingNodes-main，应该是这样
